version: "3.9"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${CC_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CC_MYSQL_DATABASE}
      MYSQL_USER: ${CC_MYSQL_USER}
      MYSQL_PASSWORD: ${CC_MYSQL_PASSWORD}
    volumes:
      - bin:/usr/bin
      - db:/var/lib/mysql

  site:
    build: .
    working_dir: /var/www/html
    depends_on:
      - db
    ports:
      - "${CC_WORDPRESS_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: ${CC_WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${CC_WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${CC_WORDPRESS_DB_PASSWORD}
      BOOTSTRAP_WP_TITLE: ${BOOTSTRAP_WP_TITLE}
      BOOTSTRAP_WP_ADMIN_USER: ${BOOTSTRAP_WP_ADMIN_USER}
      BOOTSTRAP_WP_ADMIN_PASSWORD: ${BOOTSTRAP_WP_ADMIN_PASSWORD}
      BOOTSTRAP_WP_ADMIN_EMAIL: ${BOOTSTRAP_WP_ADMIN_EMAIL}
      BOOTSTRAP_WP_URL: ${BOOTSTRAP_WP_URL}
    volumes:
      - bin:/usr/bin
      - site:/var/www/html
      - db:/var/lib/mysql
      - ./db:/home/${BOOTSTRAP_WP_ADMIN_USER}/db
      - ./wp-content:/var/www/html/wp-content
      - ./src/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./src/bootstrap.sh:/usr/local/bin/bootstrap
      - ./src/export.sh:/usr/local/bin/db-export

volumes:
  bin:
  site:
  db:
